import type { Order } from "./types";

// ============================================================
// サンプル受注データ (要件定義書 §7 を基に 8 件に拡張)
//  - ORD-001 正常 / 002 A読み取り失敗 / 003 B一部虫食い
//  - ORD-004 C相手先不備 / 005 Dバリデーションエラー
//  - ORD-006 正常(Teams) / 007 正常(高額・複数明細) / 008 B一部虫食い(FAX)
//  各 order.status は「AI読み取り後に確定する本来のステータス」。
//  デモ開始時はストア側で status='new' / isRead=false に伏せる。
// ============================================================

export const SAMPLE_ORDERS: Order[] = [
  // ---------------------------------------------------------- 正常
  {
    id: "ORD-001",
    receivedAt: "2026-07-01T09:12:00+09:00",
    channel: "email_pdf",
    sourceName: "メール添付PDF",
    customerName: "株式会社東京ストア",
    customerContactName: "佐藤様",
    customerContactAddress: "sato@tokyo-store.example.com",
    orderDate: "2026-07-01",
    requestedDeliveryDate: "2026-07-10",
    deliveryAddress: "東京都港区赤坂1-1-1",
    items: [
      { lineNo: 1, productCode: "HD-001", productName: "プレミアム健康ドリンク 24本入", quantity: 50, unit: "ケース", unitPrice: 3200, amount: 160000 },
    ],
    subtotalAmount: 160000,
    taxAmount: 16000,
    totalAmount: 176000,
    status: "read_completed",
    exceptionType: null,
    assignedTo: "ai",
    missingFields: [],
    validationErrors: [],
    aiConfidenceScore: 0.96,
    aiSummary: "必要項目がすべて揃っており、自動登録可能です。",
    recommendedAction: "基幹システムへ自動入力してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "email",
      header: "件名：注文書送付の件 / 差出人：株式会社東京ストア 佐藤 <sato@tokyo-store.example.com> / 添付：発注書_20260701.pdf",
      body: [
        "─────────────  発  注  書  ─────────────",
        "発注日：2026年7月1日            発注No：TS-20260701-08",
        "発注元：株式会社東京ストア  仕入部  佐藤",
        "納品先：東京都港区赤坂1-1-1",
        "希望納品日：2026年7月10日",
        "",
        " 商品コード   商品名                      数量    単価      金額",
        " HD-001      プレミアム健康ドリンク 24本入  50ケース ¥3,200  ¥160,000",
        "",
        "                              小計    ¥160,000",
        "                              消費税  ¥16,000",
        "                              合計    ¥176,000",
        "─────────────────────────────────────",
      ].join("\n"),
    },
  },

  // ---------------------------------------------------------- A 読み取り失敗
  {
    id: "ORD-002",
    receivedAt: "2026-07-01T10:04:00+09:00",
    channel: "fax_image",
    sourceName: "スマホ撮影FAX画像",
    customerName: "大阪リテール株式会社",
    customerContactName: null,
    customerContactAddress: null,
    orderDate: "2026-07-01",
    requestedDeliveryDate: null,
    deliveryAddress: null,
    items: [
      { lineNo: 1, productCode: null, productName: null, quantity: null, unit: null, unitPrice: null, amount: null },
    ],
    subtotalAmount: null,
    taxAmount: null,
    totalAmount: null,
    status: "internal_review_required",
    exceptionType: "ocr_failed",
    assignedTo: "internal_user",
    missingFields: [
      { fieldKey: "items.productName", fieldLabel: "商品名", reason: "FAX画像が不鮮明で読み取れませんでした。", requiredBy: "internal_user" },
      { fieldKey: "items.quantity", fieldLabel: "数量", reason: "FAX画像が不鮮明で読み取れませんでした。", requiredBy: "internal_user" },
    ],
    validationErrors: [],
    aiConfidenceScore: 0.32,
    aiSummary: "画像の解像度が低く、商品名と数量を特定できません。",
    recommendedAction: "原本を確認して手入力してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "fax_image",
      header: "スマホ撮影FAX画像 (傾き・かすれあり)",
      faxLines: [
        { text: "FAX 注文書   大阪リテール株式会社", readable: true },
        { text: "発注日 2026/7/1", readable: true },
        { text: "商品名：██▒▒健康██▒▒（判読不可）", readable: false },
        { text: "数量：▒▒ケース（かすれ）", readable: false },
        { text: "納品希望日：▒▒/▒▒（判読不可）", readable: false },
        { text: "納品先：██████（にじみ）", readable: false },
        { text: "担当：（署名かすれ）", readable: false },
      ],
    },
  },

  // ---------------------------------------------------------- B 一部虫食い
  {
    id: "ORD-003",
    receivedAt: "2026-07-01T10:31:00+09:00",
    channel: "email_body",
    sourceName: "メール本文",
    customerName: "関東ドラッグ株式会社",
    customerContactName: "田中様",
    customerContactAddress: "tanaka@kanto-drug.example.com",
    orderDate: "2026-07-01",
    requestedDeliveryDate: null,
    deliveryAddress: "埼玉県さいたま市中央区1-2-3",
    items: [
      { lineNo: 1, productCode: "BS-010", productName: "ビューティーサプリA", quantity: 100, unit: "ケース", unitPrice: 2400, amount: 240000 },
    ],
    subtotalAmount: 240000,
    taxAmount: 24000,
    totalAmount: 264000,
    status: "internal_review_required",
    exceptionType: "partial_missing",
    assignedTo: "internal_user",
    missingFields: [
      { fieldKey: "requestedDeliveryDate", fieldLabel: "希望納品日", reason: "メール本文中に候補日らしき記載はありますが、確定日として判定できません。", requiredBy: "internal_user" },
    ],
    validationErrors: [],
    aiConfidenceScore: 0.78,
    aiSummary: "主要項目は読み取れていますが、希望納品日の確認が必要です。",
    recommendedAction: "担当者がメール本文を確認し、希望納品日を補完してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "email",
      header: "件名：注文依頼 / 差出人：関東ドラッグ株式会社 田中 <tanaka@kanto-drug.example.com>",
      body: [
        "株式会社〇〇 御中",
        "",
        "以下の商品を注文いたします。",
        "商品：ビューティーサプリA",
        "商品コード：BS-010",
        "数量：100ケース",
        "納品先：埼玉県さいたま市中央区1-2-3",
        "",
        "納品日はいつものタイミングでお願いします。",
        "",
        "関東ドラッグ株式会社",
        "田中",
      ].join("\n"),
    },
  },

  // ---------------------------------------------------------- C 相手先不備
  {
    id: "ORD-004",
    receivedAt: "2026-07-01T11:05:00+09:00",
    channel: "slack",
    sourceName: "Slackメッセージ",
    customerName: "西日本小売株式会社",
    customerContactName: "山本様",
    customerContactAddress: "slack://nishinihon-retail/yamamoto",
    orderDate: "2026-07-01",
    requestedDeliveryDate: null,
    deliveryAddress: null,
    items: [
      { lineNo: 1, productCode: "RF-022", productName: "冷凍食品セットB", quantity: 200, unit: "ケース", unitPrice: 1800, amount: 360000 },
    ],
    subtotalAmount: 360000,
    taxAmount: 36000,
    totalAmount: 396000,
    status: "customer_action_required",
    exceptionType: "customer_missing_info",
    assignedTo: "customer",
    missingFields: [
      { fieldKey: "requestedDeliveryDate", fieldLabel: "希望納品日", reason: "受注依頼内に希望納品日の記載がありません。", requiredBy: "customer" },
      { fieldKey: "deliveryAddress", fieldLabel: "納品先住所", reason: "受注依頼内に納品先住所の記載がありません。", requiredBy: "customer" },
    ],
    validationErrors: [],
    aiConfidenceScore: 0.91,
    aiSummary: "商品・数量・金額は読み取れていますが、希望納品日と納品先住所が取引先から提示されていません。",
    recommendedAction: "取引先に不足情報の追記・再送を依頼してください。",
    draftReply: {
      channel: "slack",
      to: "slack://nishinihon-retail/yamamoto",
      subject: null,
      body: "ご注文内容を確認したところ、希望納品日と納品先住所が未記載でした。お手数ですが、上記2点を追記のうえ再送いただけますでしょうか。",
      editable: true,
      status: "draft",
    },
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "chat",
      header: "Slack #受注-西日本小売  |  西日本小売 山本",
      body: [
        "西日本小売 山本  11:05",
        "冷凍食品セットBを200ケースお願いします。",
        "商品コードはRF-022です。",
        "納品日と納品先は追って共有します。",
      ].join("\n"),
    },
  },

  // ---------------------------------------------------------- D バリデーションエラー
  {
    id: "ORD-005",
    receivedAt: "2026-07-01T13:20:00+09:00",
    channel: "edi",
    sourceName: "EDIデータ",
    customerName: "九州スーパー株式会社",
    customerContactName: "井上様",
    customerContactAddress: "inoue@kyushu-super.example.com",
    orderDate: "2026-07-01",
    requestedDeliveryDate: "2026-07-12",
    deliveryAddress: "福岡県福岡市博多区1-2-3",
    items: [
      { lineNo: 1, productCode: "NM-999", productName: "即席麺セットC", quantity: 300, unit: "ケース", unitPrice: 980, amount: 294000 },
    ],
    subtotalAmount: 294000,
    taxAmount: 29400,
    totalAmount: 323400,
    status: "internal_review_required",
    exceptionType: "validation_error",
    assignedTo: "internal_user",
    missingFields: [],
    validationErrors: [
      { fieldKey: "items.productCode", fieldLabel: "商品コード", errorType: "unknown_master", message: "商品コード NM-999 が商品マスタに存在しません。", requiredBy: "internal_user" },
    ],
    aiConfidenceScore: 0.94,
    aiSummary: "受注内容は読み取れていますが、商品コードが商品マスタと一致しません。",
    recommendedAction: "商品コードを確認し、正しい商品コードへ修正してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "edi",
      header: "EDI 受信データ (CSV)",
      body: [
        "customer_name,order_date,delivery_date,product_code,product_name,quantity,unit_price,delivery_address",
        "九州スーパー株式会社,2026-07-01,2026-07-12,NM-999,即席麺セットC,300,980,福岡県福岡市博多区1-2-3",
      ].join("\n"),
    },
  },

  // ---------------------------------------------------------- 正常 (Teams)
  {
    id: "ORD-006",
    receivedAt: "2026-07-01T14:02:00+09:00",
    channel: "teams",
    sourceName: "Teamsメッセージ",
    customerName: "北海道フーズ株式会社",
    customerContactName: "鈴木様",
    customerContactAddress: "teams://hokkaido-foods/suzuki",
    orderDate: "2026-07-01",
    requestedDeliveryDate: "2026-07-09",
    deliveryAddress: "北海道札幌市中央区2-4-6",
    items: [
      { lineNo: 1, productCode: "DR-051", productName: "オーガニック青汁 30包", quantity: 80, unit: "ケース", unitPrice: 2800, amount: 224000 },
    ],
    subtotalAmount: 224000,
    taxAmount: 22400,
    totalAmount: 246400,
    status: "read_completed",
    exceptionType: null,
    assignedTo: "ai",
    missingFields: [],
    validationErrors: [],
    aiConfidenceScore: 0.95,
    aiSummary: "必要項目がすべて揃っており、自動登録可能です。",
    recommendedAction: "基幹システムへ自動入力してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "chat",
      header: "Microsoft Teams  |  北海道フーズ 鈴木",
      body: [
        "北海道フーズ 鈴木  14:02",
        "いつもお世話になっております。下記発注いたします。",
        "・オーガニック青汁 30包 (DR-051) を 80ケース",
        "・納品希望日：2026/7/9",
        "・納品先：北海道札幌市中央区2-4-6",
        "よろしくお願いいたします。",
      ].join("\n"),
    },
  },

  // ---------------------------------------------------------- 正常 (高額・複数明細)
  {
    id: "ORD-007",
    receivedAt: "2026-07-01T15:40:00+09:00",
    channel: "email_pdf",
    sourceName: "メール添付PDF",
    customerName: "中部流通株式会社",
    customerContactName: "加藤様",
    customerContactAddress: "kato@chubu-ryutsu.example.com",
    orderDate: "2026-07-01",
    requestedDeliveryDate: "2026-07-15",
    deliveryAddress: "愛知県名古屋市中区3-5-7",
    items: [
      { lineNo: 1, productCode: "SP-100", productName: "高濃度プロテイン 1kg", quantity: 150, unit: "ケース", unitPrice: 4800, amount: 720000 },
      { lineNo: 2, productCode: "SP-101", productName: "プロテインシェイカー", quantity: 150, unit: "個", unitPrice: 600, amount: 90000 },
    ],
    subtotalAmount: 810000,
    taxAmount: 81000,
    totalAmount: 891000,
    status: "read_completed",
    exceptionType: null,
    assignedTo: "ai",
    missingFields: [],
    validationErrors: [],
    aiConfidenceScore: 0.97,
    aiSummary: "必要項目がすべて揃っており、自動登録可能です。複数明細も正しく抽出しました。",
    recommendedAction: "基幹システムへ自動入力してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "email",
      header: "件名：発注書の送付 / 差出人：中部流通株式会社 加藤 <kato@chubu-ryutsu.example.com> / 添付：PO_chubu_0701.pdf",
      body: [
        "─────────────  発  注  書  ─────────────",
        "発注日：2026年7月1日            発注No：CB-0701-114",
        "発注元：中部流通株式会社  購買部  加藤",
        "納品先：愛知県名古屋市中区3-5-7",
        "希望納品日：2026年7月15日",
        "",
        " 商品コード   商品名               数量     単価      金額",
        " SP-100      高濃度プロテイン 1kg   150ケース ¥4,800  ¥720,000",
        " SP-101      プロテインシェイカー   150個    ¥600    ¥90,000",
        "",
        "                          小計    ¥810,000",
        "                          消費税  ¥81,000",
        "                          合計    ¥891,000",
        "─────────────────────────────────────",
      ].join("\n"),
    },
  },

  // ---------------------------------------------------------- B 一部虫食い (FAX)
  {
    id: "ORD-008",
    receivedAt: "2026-07-01T16:18:00+09:00",
    channel: "fax_image",
    sourceName: "複合機FAX画像",
    customerName: "東北商事株式会社",
    customerContactName: "高橋様",
    customerContactAddress: null,
    orderDate: "2026-07-01",
    requestedDeliveryDate: null,
    deliveryAddress: "宮城県仙台市青葉区1-3-5",
    items: [
      { lineNo: 1, productCode: "FZ-030", productName: "冷凍うどんセット", quantity: 120, unit: "ケース", unitPrice: 1500, amount: 180000 },
    ],
    subtotalAmount: 180000,
    taxAmount: 18000,
    totalAmount: 198000,
    status: "internal_review_required",
    exceptionType: "partial_missing",
    assignedTo: "internal_user",
    missingFields: [
      { fieldKey: "requestedDeliveryDate", fieldLabel: "希望納品日", reason: "手書き欄がかすれており、確定日として読み取れませんでした。", requiredBy: "internal_user" },
    ],
    validationErrors: [],
    aiConfidenceScore: 0.72,
    aiSummary: "商品名・数量・納品先は読み取れましたが、希望納品日の手書き欄が判読できません。",
    recommendedAction: "担当者が原本の手書き欄を確認し、希望納品日を補完してください。",
    draftReply: null,
    coreSystemInput: null,
    logs: [],
    sourcePreview: {
      kind: "fax_image",
      header: "複合機FAX画像 (手書き欄あり)",
      faxLines: [
        { text: "注文書   東北商事株式会社   高橋", readable: true },
        { text: "商品：冷凍うどんセット (FZ-030)", readable: true },
        { text: "数量：120ケース", readable: true },
        { text: "納品先：宮城県仙台市青葉区1-3-5", readable: true },
        { text: "希望納品日：７/▒▒（手書き・かすれ）", readable: false },
      ],
    },
  },
];
